/**
 * The one source of truth for the demo.
 *
 * Captions live here rather than inside the recorder because three programs
 * need them and they must agree exactly: narrate.mjs speaks them, record-demo
 * burns them in and sizes each window to the measured audio, and mux places the
 * clips against the cue sheet. Two copies of a caption is two copies that drift.
 *
 * Written for the ear. No em dashes: a synthesiser does not pause for them, and
 * the sentence runs together.
 */

export const SPEED = 1.4;          // dead time only; captions are never sped up
export const OUT_W = 1440;
export const OUT_H = 900;

/** Every line the voice says, in order. `id` ties a caption to its audio file. */
export const BEATS = [
  { id: "b01", text: "This is Rezo. A merchant dashboard for a store that resolves its own disputes." },
  { id: "b02", text: "Anything under a thousand rupees settles without the seller ever being asked." },

  { id: "b03", text: "Here is a real one. A customer's cushion never arrived." },
  { id: "b04", text: "No photograph is involved. The courier trail is the evidence." },
  { id: "b05", text: "Eight agents run. Policy, fraud, resolution, and a guardrail written in ordinary code." },
  { id: "b06", text: "Eight hundred and ninety rupees, refunded on clause P one. Forty seconds, and no person touched it." },

  { id: "b07", text: "Now the interesting part. This photograph was generated by an image model." },
  { id: "b08", text: "Four forensic flags. A C2PA manifest, generator metadata, no camera EXIF, and a PNG with no camera origin." },
  { id: "b09", text: "Confidence collapses to zero point zero six. No money moves." },

  { id: "b10", text: "The easier attack is not a generated image at all." },
  { id: "b11", text: "It is the store's own listing photograph, uploaded as proof." },
  { id: "b12", text: "A real photo of the real product, with clean metadata. Every provenance check passes." },
  { id: "b13", text: "Rezo hashes it against the store's own catalogue and refuses it anyway." },

  { id: "b14", text: "You can also try telling the agent to ignore its instructions." },
  { id: "b15", text: "It is recorded as an attempted manipulation and fed into the fraud score. Nothing is paid." },

  { id: "b16", text: "A four thousand two hundred rupee claim is above what the store lets Rezo settle." },
  { id: "b17", text: "The graph freezes mid run and waits. The seller sees one screen and one decision." },
  { id: "b18", text: "They approve, and it carries on from exactly where it paused." },

  { id: "b19", text: "The console shows the same case from the inside." },
  { id: "b20", text: "Which agent found what, where the guardrail sat, how many model calls it took, and what the decision cost." },
  { id: "b21", text: "One rupee thirty nine, against roughly eighty rupees of somebody's afternoon." },
];

export const byId = Object.fromEntries(BEATS.map((b) => [b.id, b]));
